
// Code generated by WebUtils.GenTplFunc DO NOT EDIT
package funcs
import (
 
     "html/template"
 
 )
var FuncMap=map[string]interface{}{
 
   "Box" :func (txt string) template.HTML {
	return template.HTML("<div class='.box'>" + txt + "</div>")
},
  
   "Strong" :func (txt string) template.HTML {
	return template.HTML("<strong style='color:red'>" + txt + "</strong>")
},
  
   "Test" :func () string {
	return "aaa"
},
  
}
			